const DATABASE_NAME = "@gameplay";

const COLLECTION_USERS = `${DATABASE_NAME}: user`;
const COLLECTION_APPOINTMENTs = `${DATABASE_NAME}: appointment`;

export { COLLECTION_USERS, COLLECTION_APPOINTMENTs };
